// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhik4eCXd4_jKzv_qM3euVdEAdiuf83KM',
    appId: '1:337197755458:web:cf326b4b9f1fa60c64d1db',
    messagingSenderId: '337197755458',
    projectId: 'flashchat-729ee',
    authDomain: 'flashchat-729ee.firebaseapp.com',
    storageBucket: 'flashchat-729ee.appspot.com',
    measurementId: 'G-2RPFZ62E4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrtU_RlqjfHUol4OUkPgruOkA51HAnckA',
    appId: '1:337197755458:android:013a1297ccdd213264d1db',
    messagingSenderId: '337197755458',
    projectId: 'flashchat-729ee',
    storageBucket: 'flashchat-729ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbaWaZQ1PR6EQRHpXVsjZF27AmXjp6vs',
    appId: '1:337197755458:ios:5713c08096df269c64d1db',
    messagingSenderId: '337197755458',
    projectId: 'flashchat-729ee',
    storageBucket: 'flashchat-729ee.appspot.com',
    iosClientId: '337197755458-j0539kgbhmvdlffue1ue1if0rnkfjjam.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbaWaZQ1PR6EQRHpXVsjZF27AmXjp6vs',
    appId: '1:337197755458:ios:5713c08096df269c64d1db',
    messagingSenderId: '337197755458',
    projectId: 'flashchat-729ee',
    storageBucket: 'flashchat-729ee.appspot.com',
    iosClientId: '337197755458-j0539kgbhmvdlffue1ue1if0rnkfjjam.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
